name: Tag Python Package Version
on:
  push:
    branches:
      - main

jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Read version & tag
        run: |
          version=$(python -c "from src.awesome_code.__about__ import __version__ as version; print(version)")
          echo "Version: $version"
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git tag $version
          git push origin $version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}